spring:
    data:
        mongodb:
            database: UserDB
            host: localhost
            port: 27017
    jackson:
        default-property-inclusion: NON_NULL

app:
    auth:
        user:
            password: password
            email: user@mail.com


register:
    success:
        url: http://localhost:9091/email
